# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagenes',
            field=models.ManyToManyField(related_name='noticias', to='noticias.Imagen'),
        ),
    ]
